### ISSUE TITLE
How to change font?

### ISSUE THREAD

**Issue by Mike0625** [py-plugin-apps/petpet#1]
The built-in font does not support Chinese,how to change it.
插件自带字体不支持中文，如何更换？

**Comment by realhuhu** [comment]
可以提供图片示例吗，我看看

**Comment by Mike0625** [comment]
OK

**Comment by Mike0625** [comment]
![IMG_20220819_161845](https://user-images.githubusercontent.com/67299215/185576083-48c48c52-d54f-4a97-828d-d634d995e3fa.jpg)
![IMG_20220819_161736](https://user-images.githubusercontent.com/67299215/185576094-4ba6a259-778b-4746-a0a2-853218ce137d.jpg)

**Comment by Mike0625** [comment]
还有就是：希望可以加入最开始的python-plugin有的功能：表情制作可以通过引用图片来制作，也可以通过先发图，再发消息来做（图和消息不是一个人发的也可以）[doge]

**Comment by realhuhu** [comment]
> 还有就是：希望可以加入最开始的python-plugin有的功能：表情制作可以通过引用图片来制作，也可以通过先发图，再发消息来做（图和消息不是一个人发的也可以）[doge]

以后会支持，因为需要对py-plugin整体修改

**Comment by realhuhu** [comment]
这应该是服务器没装字体

**Comment by Mike0625** [comment]
我的nonebot-plugin-imageutils里有中文字体[doge]

**Comment by Mike0625** [comment]
> 

em那怎么更换字体？[双手合十]

**Comment by Mike0625** [comment]
还有就是建议在这个的所有正则表达式的#后面加个*

非常感谢

**Comment by Mike0625** [comment]
> > 还有就是：希望可以加入最开始的python-plugin有的功能：表情制作可以通过引用图片来制作，也可以通过先发图，再发消息来做（图和消息不是一个人发的也可以）[doge]
> 
> 以后会支持，因为需要对py-plugin整体修改

OK感谢

**Comment by realhuhu** [comment]
> 还有就是建议在这个的所有正则表达式的#后面加个*
> 
> 非常感谢

能带额外参数的表情，正则结尾都没有$，可以加自己的话

**Comment by realhuhu** [comment]
字体问题先试试在linux上多装几种字体

**Comment by Mike0625** [comment]
> 字体问题先试试在linux上多装几种字体

我把原来的字体复制到了py-plugin/apps/petpet/py/resources/fonts/里面，貌似不管用，我去试试系统装字体

**Comment by Mike0625** [comment]
> > 还有就是建议在这个的所有正则表达式的#后面加个*
> > 非常感谢
> 
> 能带额外参数的表情，正则结尾都没有$，可以加自己的话

嗯，是因为我和群友懒得写#😂

**Comment by Mike0625** [comment]
> 字体问题先试试在linux上多装几种字体

！好像成功解决了

**Comment by Mike0625** [comment]
非常感谢！！

**Comment by Mike0625** [comment]
![IMG_20220819_165557](https://user-images.githubusercontent.com/67299215/185583873-605ddf5e-2419-40c7-af10-f301e8454a7c.jpg)
这个看样子是字体问题，建议指定字体[双手合十]

**Comment by realhuhu** [comment]
> ![IMG_20220819_165557](https://user-images.githubusercontent.com/67299215/185583873-605ddf5e-2419-40c7-af10-f301e8454a7c.jpg) 这个看样子是字体问题，建议指定字体[双手合十]

petpet的字符画比较拉跨，我有一个专门做字符画的插件，估计明天会上传

**Comment by Mike0625** [comment]
行
